blueprint:
  name: Shelly unavailability detection & notification
  description: Notifies immediately when any Shelly entity becomes unavailable.
  domain: automation
  input:
    exclude:
      name: Excluded Entities
      description: Shelly entities to exclude from detection. Only entities are supported, devices must be expanded!
      default:
        entity_id: []
      selector:
        target:
          entity: {}
    actions:
      name: Actions
      description: Notifications or similar to be run. {{entities}} is replaced with the names of Shelly entities currently unavailable.
      selector:
        action: {}
  source_url: https://github.com/TAPAlves/Blueprint
variables:
  exclude: !input exclude
  entities: >-
    {% set result = namespace(unavailable=[]) %}
    {% for state in states if state.entity_id.startswith('shelly') and state.state == 'unavailable' and state.entity_id not in exclude.entity_id %}
      {% set result.unavailable = result.unavailable + [state.name] %}
    {% endfor %}
    {{ result.unavailable | join(', ') }}
trigger:
  - platform: template
    value_template: >-
      {{ states
        | selectattr('entity_id', 'search', '^shelly')
        | selectattr('state', 'eq', 'unavailable')
        | rejectattr('entity_id', 'in', exclude.entity_id)
        | list
        | count > 0 }}
condition:
  - '{{ entities != "" }}'
action:
  - choose: []
    default: !input actions
mode: single
