blueprint:
  name: Notificação de Entidade Indisponível
  description: Envia notificação para o telemóvel quando qualquer entidade fica indisponível. Ideal para Shelly.
  domain: automation
  input:
    notify_device:
      name: Dispositivo para notificação
      description: Escolha o telemóvel para o qual enviar a notificação
      selector:
        device:
          integration: mobile_app
    exclude_entities:
      name: Entidades a excluir (opcional)
      description: Entidades que não devem gerar notificação
      default: []
      selector:
        entity: {}

trigger:
  - platform: state
    from: ~
    to: 'unavailable'

condition:
  # Exclui entidades selecionadas
  - condition: template
    value_template: >
      {{ trigger.entity_id not in iif(is_defined(exclude_entities), exclude_entities, []) }}

action:
  - service: notify.mobile_app_{{ device_attr(notify_device, 'name')|lower|replace(' ', '_') }}
    data:
      message: "A entidade {{ trigger.to_state.name or trigger.entity_id }} ficou indisponível!"
      title: "Entidade indisponível!"

mode: single
